spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io

README-zh.md
README.md

update readme file

---

i18n/zh-cn/docusaurus-plugin-content-docs/current/user-guide/nacos/advanced-guide.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/user-guide/nacos/overview.md

optimize nacos doc

---

i18n/zh-cn/docusaurus-plugin-content-docs/current/user-guide/rocketmq/advanced-guide.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/user-guide/rocketmq/overview.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/user-guide/rocketmq/quick-start.md

add rocketmq doc

---

CONTRIBUTING-en.md
CONTRIBUTING.md

- For https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/issues/23
Add contrinuting doc.

add contrinuting doc

---

i18n/zh-cn/code.json

update index page

---

i18n/zh-cn/docusaurus-plugin-content-docs/current/overview/faq.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/user-guide/nacos/overview.md

- For https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/issues/23
- Add sca faq.

Add sca faq [WIP]

---

i18n/en-us/docusaurus-plugin-content-docs/version-2022.0.0.0-RC1/user-guide/graalvm/advanced-guide.md
i18n/en-us/docusaurus-plugin-content-docs/version-2022.0.0.0-RC2/user-guide/graalvm/advanced-guide.md
i18n/en-us/docusaurus-plugin-content-docs/version-2022.0.0.0/user-guide/graalvm/advanced-guide.md
versioned_docs/version-2022.0.0.0-RC1/user-guide/graalvm/advanced-guide.md
versioned_docs/version-2022.0.0.0-RC2/user-guide/graalvm/advanced-guide.md
versioned_docs/version-2022.0.0.0/reference-manual/glossary.md
versioned_docs/version-2022.0.0.0/user-guide/graalvm/advanced-guide.md
versioned_sidebars/version-2022.0.0.0-RC1-sidebars.json
versioned_sidebars/version-2022.0.0.0-RC2-sidebars.json
versioned_sidebars/version-2022.0.0.0-sidebars.json

- For https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/issues/23

optimize graalvm doc

---

i18n/en-us/docusaurus-plugin-content-docs/current/overview/faq.md
i18n/en-us/docusaurus-plugin-content-docs/version-2.2.10-RC1/overview/faq.md
i18n/en-us/docusaurus-plugin-content-docs/version-2.2.8.RELEASE/overview/faq.md
i18n/en-us/docusaurus-plugin-content-docs/version-2.2.9.RELEASE/overview/faq.md
i18n/en-us/docusaurus-plugin-content-docs/version-2021.0.1.0/overview/faq.md
i18n/en-us/docusaurus-plugin-content-docs/version-2021.0.4.0/overview/faq.md
i18n/en-us/docusaurus-plugin-content-docs/version-2021.0.5.0/overview/faq.md
i18n/en-us/docusaurus-plugin-content-docs/version-2022.0.0.0-RC1/overview/faq.md
i18n/en-us/docusaurus-plugin-content-docs/version-2022.0.0.0-RC2/overview/faq.md
i18n/en-us/docusaurus-plugin-content-docs/version-2022.0.0.0/overview/faq.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2.2.10-RC1/overview/faq.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2.2.8.RELEASE/overview/faq.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2.2.9.RELEASE/overview/faq.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2021.0.1.0/overview/faq.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2021.0.4.0/overview/faq.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2021.0.5.0/overview/faq.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2022.0.0.0-RC1/overview/faq.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2022.0.0.0-RC2/overview/faq.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2022.0.0.0/overview/faq.md

- For https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/issues/45

optimize-faq

---

i18n/zh-cn/docusaurus-plugin-content-blog/SCA-Higress-Application-Deployment.md

Add a blog about Higress

---

i18n/zh-cn/docusaurus-plugin-content-blog/SCA-Higress-Routing.md

- For https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/issues/76

fix: update blog content

---

.github/ISSUE_TEMPLATE/documentation.yaml
.github/ISSUE_TEMPLATE/website.yaml
.github/pull_request_template.md

add issue and pr template

---

i18n/zh-cn/docusaurus-plugin-content-docs-community/current/developer/developers_dev.md

feat: add developer github link

---

.markdownlint.yml
i18n/zh-cn/docusaurus-plugin-content-blog/Higress-Plugin.md

Changes:
- Adjust the md checking rules in ci to reduce the difficulty of code contribution.
- Md rule: https://docs.github.com/zh/contributing/collaborating-on-github-docs/using-the-content-linter#linting-rules

feat: update md lint rule

---

i18n/zh-cn/docusaurus-plugin-content-blog/spring-boot-to-spring-cloud-best-practice.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/best-practice/spring-boot-to-spring-cloud.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2.2.10-RC1/best-practice/spring-boot-to-spring-cloud.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2.2.8.RELEASE/best-practice/spring-boot-to-spring-cloud.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2.2.9.RELEASE/best-practice/spring-boot-to-spring-cloud.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2021.0.1.0/best-practice/spring-boot-to-spring-cloud.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2021.0.4.0/best-practice/spring-boot-to-spring-cloud.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2021.0.5.0/best-practice/spring-boot-to-spring-cloud.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2022.0.0.0-RC1/best-practice/spring-boot-to-spring-cloud.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2022.0.0.0-RC2/best-practice/spring-boot-to-spring-cloud.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2022.0.0.0/best-practice/spring-boot-to-spring-cloud.md

Changes:
update maven module comment

fix: update maven module comment

---

Dockerfile

fix: fix docker run failed

---

README.md

- For Correct Chinese in English readme.

feat: Correct Chinese in English readme

---

.markdownlint.yml
i18n/en-us/docusaurus-plugin-content-docs/version-2022.0.0.0-RC1/user-guide/nacos/quick-start.md
i18n/en-us/docusaurus-plugin-content-docs/version-2022.0.0.0-RC2/user-guide/nacos/quick-start.md
i18n/en-us/docusaurus-plugin-content-docs/version-2022.0.0.0/user-guide/nacos/quick-start.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2022.0.0.0-RC1/user-guide/nacos/quick-start.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2022.0.0.0-RC2/user-guide/nacos/quick-start.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2022.0.0.0/user-guide/nacos/quick-start.md

Fixes: https://github.com/alibaba/spring-cloud-alibaba/issues/3525#issuecomment-1876710240

feat: update nacos-docs to adapt nacos 2.2.x version

---

docusaurus.config.js

fix: fix ci

---

i18n/en-us/docusaurus-plugin-content-docs-community/current/developer/developers_dev.md
i18n/zh-cn/docusaurus-plugin-content-docs-community/current/developer/developers_dev.md

- Add new committer
- Unite en-us & zh-cn committer info tables.

community: add new committer

---

i18n/zh-cn/docusaurus-plugin-content-docs/current/overview/version-explain.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2.2.10-RC1/overview/version-explain.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2.2.8.RELEASE/overview/version-explain.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2.2.9.RELEASE/overview/version-explain.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2021.0.1.0/overview/version-explain.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2021.0.4.0/overview/version-explain.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2021.0.5.0/overview/version-explain.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2022.0.0.0-RC1/overview/version-explain.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2022.0.0.0-RC2/overview/version-explain.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2022.0.0.0/overview/version-explain.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2023.0.0.0-RC1/overview/version-explain.md

Fixes: #144 
Changes: fix: version-explain.md editUrl 404

fix: version-explain.md editUrl 404

---

docusaurus.config.js

ci: fix ci

---

google02d7da7ccae19812.html

add google search

---

src/components/common/Header/index.astro

fix: cnpliot style

---

src/content/docs/2023/zh-cn/user-guide/seata/quick-start.md

fix: update seata doc example url

---

src/components/markdownSet/SimpleContainer.astro

fix: fix scroll style

---

src/components/starlight/Head.astro

feat:add mate

---

src/components/cloud/FunctionalCompare/index.jsx
src/components/home/OverViewImage/components/common/Panel.jsx
src/utils/util.ts

fix: 不同版本对比兼容

---

package-lock.json
package.json

fix: build构建问题

---

package.json
src/components/common/Header/Search.astro
src/components/common/Header/index.astro

feat:新增搜索功能

---

src/content/blog/SCA-gvr7dx_awbbpb_tp0pgbnsg4bef0x1.mdx

fix: sca video markdown

---

src/constant.ts
src/content/blog/SCA-gvr7dx_awbbpb_tp0pgbnsg4bef0x1.mdx

Hide navbar

---

src/components/common/Header/index.astro

fix: delete copilot

---

src/content/faq/SCA-user-question-history16422.md
src/content/faq/SCA-user-question-history16423.md
src/content/faq/SCA-user-question-history16424.md
src/content/faq/SCA-user-question-history16425.md
src/content/faq/SCA-user-question-history16426.md
src/content/faq/SCA-user-question-history16427.md

update By Robot2024-08-07 17:02:43

---

package-lock.json

fix lock.json

---

package-lock.json
package.json

Fix goat-ui 

---

src/components/ai/Footer.astro

fix ai Ding

---

src/content/blog/faq/SCA-question-history-17098.md
src/content/faq/SCA-user-question-history17096.md
src/content/faq/SCA-user-question-history17097.md
src/content/faq/SCA-user-question-history17098.md
src/layouts/BaseLayout.astro
src/pages/blog/[...slug].astro
src/pages/en/blog/[...slug].astro
src/pages/en/faq/[...slug].astro
src/pages/en/learn/[...slug].astro
src/pages/faq/[...slug].astro
src/pages/learn/[...slug].astro

feat: update wuyi & fix keywords

---

src/components/home/Carousel.astro

fix banner ar

---

src/content/ai/get-started.md

Fixes: ai dependency version number is incorrect
Changes:
1.0.0-m2  -> 1.0.0-M2

docs:Update get-started.md

---

src/components/home/HomeIntroduce.astro
src/components/starlight/Head.astro

Seo20141008

---

i18n/en-us/docusaurus-plugin-content-docs/current/user-guide/nacos/advanced-guide.md
i18n/en-us/docusaurus-plugin-content-docs/version-2.2.10-RC1/user-guide/nacos/advanced-guide.md
i18n/en-us/docusaurus-plugin-content-docs/version-2.2.8.RELEASE/user-guide/nacos/advanced-guide.md
i18n/en-us/docusaurus-plugin-content-docs/version-2.2.9.RELEASE/user-guide/nacos/advanced-guide.md
i18n/en-us/docusaurus-plugin-content-docs/version-2021.0.1.0/user-guide/nacos/advanced-guide.md
i18n/en-us/docusaurus-plugin-content-docs/version-2021.0.4.0/user-guide/nacos/advanced-guide.md
i18n/en-us/docusaurus-plugin-content-docs/version-2021.0.5.0/user-guide/nacos/advanced-guide.md
i18n/en-us/docusaurus-plugin-content-docs/version-2022.0.0.0-RC1/user-guide/nacos/advanced-guide.md
i18n/en-us/docusaurus-plugin-content-docs/version-2022.0.0.0-RC2/user-guide/nacos/advanced-guide.md
i18n/en-us/docusaurus-plugin-content-docs/version-2022.0.0.0/user-guide/nacos/advanced-guide.md
i18n/en-us/docusaurus-plugin-content-docs/version-2023.0.0.0-RC1/user-guide/nacos/advanced-guide.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/user-guide/nacos/advanced-guide.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2.2.10-RC1/user-guide/nacos/advanced-guide.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2.2.8.RELEASE/user-guide/nacos/advanced-guide.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2.2.9.RELEASE/user-guide/nacos/advanced-guide.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2021.0.1.0/user-guide/nacos/advanced-guide.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2021.0.4.0/user-guide/nacos/advanced-guide.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2021.0.5.0/user-guide/nacos/advanced-guide.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2022.0.0.0-RC1/user-guide/nacos/advanced-guide.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2022.0.0.0-RC2/user-guide/nacos/advanced-guide.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2022.0.0.0/user-guide/nacos/advanced-guide.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-2023.0.0.0-RC1/user-guide/nacos/advanced-guide.md

Fixes: https://github.com/alibaba/spring-cloud-alibaba/issues/3675

docs: update nacos.discovery filed

---

src/constant.ts

feat: 运营点位更新

---

src/components/ai/Footer.astro
src/components/common/Footer.astro
src/i18n/en/ui.ts
src/i18n/zh-cn/ui.ts

add footer friendLinks

---

src/components/common/Header/index.astro

changeAIstyle

---

src/content/docs/2023/zh-cn/user-guide/nacos/advanced-guide.md

fix: update nacos docs
